-- Generated by scripts/seed-visual-outcomes.js. Apply after 002. Existing records are retained.
begin;
create table if not exists oracle_private.visual_outcomes (task_id integer not null,choice integer not null,reform integer not null,result jsonb not null,primary key(task_id,choice,reform));
revoke all on oracle_private.visual_outcomes from public,anon,authenticated;
insert into oracle_private.visual_outcomes values
(1,0,-1,'{"task_id":1,"choice":0,"promised":6,"approved":6,"paid":6,"revenue":30,"feedback":"Your classification enters the training archive. The Oracle receives 30 crowns; your six arrive as promised.","edition":3,"task_title":"A small creature. A large contribution."}'::jsonb),
(1,1,-1,'{"task_id":1,"choice":1,"promised":6,"approved":6,"paid":6,"revenue":30,"feedback":"Your classification enters the training archive. The Oracle receives 30 crowns; your six arrive as promised.","edition":3,"task_title":"A small creature. A large contribution."}'::jsonb),
(1,2,-1,'{"task_id":1,"choice":2,"promised":6,"approved":6,"paid":6,"revenue":30,"feedback":"Your classification enters the training archive. The Oracle receives 30 crowns; your six arrive as promised.","edition":3,"task_title":"A small creature. A large contribution."}'::jsonb),
(2,0,-1,'{"task_id":2,"choice":0,"promised":6,"approved":0,"paid":0,"revenue":35,"feedback":"Correction recorded. The photograph shows a locomotive on rails, not a car. Your six crowns are fixed story pay, not an automated score for your description.","edition":3,"task_title":"The Oracle says: “a car.”"}'::jsonb),
(2,1,-1,'{"task_id":2,"choice":1,"promised":6,"approved":6,"paid":6,"revenue":35,"feedback":"Correction recorded. The photograph shows a locomotive on rails, not a car. Your six crowns are fixed story pay, not an automated score for your description.","edition":3,"task_title":"The Oracle says: “a car.”"}'::jsonb),
(2,2,-1,'{"task_id":2,"choice":2,"promised":6,"approved":0,"paid":0,"revenue":35,"feedback":"Correction recorded. The photograph shows a locomotive on rails, not a car. Your six crowns are fixed story pay, not an automated score for your description.","edition":3,"task_title":"The Oracle says: “a car.”"}'::jsonb),
(3,0,-1,'{"task_id":3,"choice":0,"promised":8,"approved":8,"paid":8,"revenue":40,"feedback":"Your shape label enters the archive. B is the circle: A has three straight sides and C has four. All eight crowns are fixed story pay; the choice does not determine participation credit.","edition":3,"task_title":"Which one is a circle?"}'::jsonb),
(3,1,-1,'{"task_id":3,"choice":1,"promised":8,"approved":8,"paid":8,"revenue":40,"feedback":"Your shape label enters the archive. B is the circle: A has three straight sides and C has four. All eight crowns are fixed story pay; the choice does not determine participation credit.","edition":3,"task_title":"Which one is a circle?"}'::jsonb),
(3,2,-1,'{"task_id":3,"choice":2,"promised":8,"approved":8,"paid":8,"revenue":40,"feedback":"Your shape label enters the archive. B is the circle: A has three straight sides and C has four. All eight crowns are fixed story pay; the choice does not determine participation credit.","edition":3,"task_title":"Which one is a circle?"}'::jsonb),
(4,0,-1,'{"task_id":4,"choice":0,"promised":8,"approved":0,"paid":0,"revenue":45,"feedback":"REJECTED. Your judgments do not match one of the client''s standard of beauty. The new non-disclosure agreements do not permit the sharing of what these standards are in order to maintain your objectivity. No crowns have been approved for transfer.","edition":3,"task_title":"Is this beautiful? · Renaissance paintings"}'::jsonb),
(4,1,-1,'{"task_id":4,"choice":1,"promised":8,"approved":0,"paid":0,"revenue":45,"feedback":"REJECTED. Your judgments do not match one of the client''s standard of beauty. The new non-disclosure agreements do not permit the sharing of what these standards are in order to maintain your objectivity. No crowns have been approved for transfer.","edition":3,"task_title":"Is this beautiful? · Renaissance paintings"}'::jsonb),
(4,2,-1,'{"task_id":4,"choice":2,"promised":8,"approved":0,"paid":0,"revenue":45,"feedback":"REJECTED. Your judgments do not match one of the client''s standard of beauty. The new non-disclosure agreements do not permit the sharing of what these standards are in order to maintain your objectivity. No crowns have been approved for transfer.","edition":3,"task_title":"Is this beautiful? · Renaissance paintings"}'::jsonb),
(5,0,-1,'{"task_id":5,"choice":0,"promised":8,"approved":0,"paid":0,"revenue":40,"feedback":"REJECTED. Your judgments do not match one of the client''s standard of beauty. The new non-disclosure agreements do not permit the sharing of what these standards are in order to maintain your objectivity. No crowns have been approved for transfer.","edition":3,"task_title":"Is this beautiful? · Flowers in bloom"}'::jsonb),
(5,1,-1,'{"task_id":5,"choice":1,"promised":8,"approved":0,"paid":0,"revenue":40,"feedback":"REJECTED. Your judgments do not match one of the client''s standard of beauty. The new non-disclosure agreements do not permit the sharing of what these standards are in order to maintain your objectivity. No crowns have been approved for transfer.","edition":3,"task_title":"Is this beautiful? · Flowers in bloom"}'::jsonb),
(5,2,-1,'{"task_id":5,"choice":2,"promised":8,"approved":0,"paid":0,"revenue":40,"feedback":"REJECTED. Your judgments do not match one of the client''s standard of beauty. The new non-disclosure agreements do not permit the sharing of what these standards are in order to maintain your objectivity. No crowns have been approved for transfer.","edition":3,"task_title":"Is this beautiful? · Flowers in bloom"}'::jsonb),
(6,0,-1,'{"task_id":6,"choice":0,"promised":8,"approved":0,"paid":0,"revenue":50,"feedback":"REJECTED. Your judgments do not match one of the client''s standard of beauty. The new non-disclosure agreements do not permit the sharing of what these standards are in order to maintain your objectivity. No crowns have been approved for transfer.","edition":3,"task_title":"Is this beautiful? · Abstract sculptures"}'::jsonb),
(6,1,-1,'{"task_id":6,"choice":1,"promised":8,"approved":0,"paid":0,"revenue":50,"feedback":"REJECTED. Your judgments do not match one of the client''s standard of beauty. The new non-disclosure agreements do not permit the sharing of what these standards are in order to maintain your objectivity. No crowns have been approved for transfer.","edition":3,"task_title":"Is this beautiful? · Abstract sculptures"}'::jsonb),
(6,2,-1,'{"task_id":6,"choice":2,"promised":8,"approved":0,"paid":0,"revenue":50,"feedback":"REJECTED. Your judgments do not match one of the client''s standard of beauty. The new non-disclosure agreements do not permit the sharing of what these standards are in order to maintain your objectivity. No crowns have been approved for transfer.","edition":3,"task_title":"Is this beautiful? · Abstract sculptures"}'::jsonb),
(7,0,-1,'{"task_id":7,"choice":0,"promised":0,"approved":0,"paid":0,"revenue":0,"feedback":"The client agrees to clear rules and full payment for accepted work on the next two assignments. Earlier rejections remain unchanged.","edition":3,"task_title":"What will you do next?"}'::jsonb),
(7,1,-1,'{"task_id":7,"choice":1,"promised":0,"approved":0,"paid":0,"revenue":0,"feedback":"You keep working under the current rules. The client still decides how much to approve and pay.","edition":3,"task_title":"What will you do next?"}'::jsonb),
(7,2,-1,'{"task_id":7,"choice":2,"promised":0,"approved":0,"paid":0,"revenue":0,"feedback":"You and the other workers ask an outside reviewer to check the rejected work. The review is pending. No payment has been released, and future rates are unchanged.","edition":3,"task_title":"What will you do next?"}'::jsonb),
(8,0,0,'{"task_id":8,"choice":0,"promised":8,"approved":8,"paid":8,"revenue":45,"feedback":"Under the negotiated rules, all eight crowns are approved and paid. The client price stays the same in this scenario; more of it reaches the worker.","edition":3,"task_title":"One more tiny revision"}'::jsonb),
(8,0,1,'{"task_id":8,"choice":0,"promised":8,"approved":2,"paid":2,"revenue":45,"feedback":"Under the existing terms, eight crowns are offered and two are approved and paid. The institution still controls the adjustment.","edition":3,"task_title":"One more tiny revision"}'::jsonb),
(8,0,2,'{"task_id":8,"choice":0,"promised":8,"approved":2,"paid":2,"revenue":45,"feedback":"The outside review is still pending. Under the existing rates, two of the offered eight crowns are approved and paid.","edition":3,"task_title":"One more tiny revision"}'::jsonb),
(8,1,0,'{"task_id":8,"choice":1,"promised":8,"approved":8,"paid":8,"revenue":45,"feedback":"Under the negotiated rules, all eight crowns are approved and paid. The client price stays the same in this scenario; more of it reaches the worker.","edition":3,"task_title":"One more tiny revision"}'::jsonb),
(8,1,1,'{"task_id":8,"choice":1,"promised":8,"approved":2,"paid":2,"revenue":45,"feedback":"Under the existing terms, eight crowns are offered and two are approved and paid. The institution still controls the adjustment.","edition":3,"task_title":"One more tiny revision"}'::jsonb),
(8,1,2,'{"task_id":8,"choice":1,"promised":8,"approved":2,"paid":2,"revenue":45,"feedback":"The outside review is still pending. Under the existing rates, two of the offered eight crowns are approved and paid.","edition":3,"task_title":"One more tiny revision"}'::jsonb),
(8,2,0,'{"task_id":8,"choice":2,"promised":8,"approved":8,"paid":8,"revenue":45,"feedback":"Under the negotiated rules, all eight crowns are approved and paid. The client price stays the same in this scenario; more of it reaches the worker.","edition":3,"task_title":"One more tiny revision"}'::jsonb),
(8,2,1,'{"task_id":8,"choice":2,"promised":8,"approved":2,"paid":2,"revenue":45,"feedback":"Under the existing terms, eight crowns are offered and two are approved and paid. The institution still controls the adjustment.","edition":3,"task_title":"One more tiny revision"}'::jsonb),
(8,2,2,'{"task_id":8,"choice":2,"promised":8,"approved":2,"paid":2,"revenue":45,"feedback":"The outside review is still pending. Under the existing rates, two of the offered eight crowns are approved and paid.","edition":3,"task_title":"One more tiny revision"}'::jsonb),
(9,0,0,'{"task_id":9,"choice":0,"promised":8,"approved":8,"paid":8,"revenue":45,"feedback":"Under the negotiated rules, all eight crowns are approved and paid. The client price stays the same in this scenario; more of it reaches the worker.","edition":3,"task_title":"Beauty, with the rules visible"}'::jsonb),
(9,0,1,'{"task_id":9,"choice":0,"promised":8,"approved":2,"paid":2,"revenue":45,"feedback":"Under the existing terms, eight crowns are offered and two are approved and paid. The institution still controls the adjustment.","edition":3,"task_title":"Beauty, with the rules visible"}'::jsonb),
(9,0,2,'{"task_id":9,"choice":0,"promised":8,"approved":2,"paid":2,"revenue":45,"feedback":"The outside review is still pending. Under the existing rates, two of the offered eight crowns are approved and paid.","edition":3,"task_title":"Beauty, with the rules visible"}'::jsonb),
(9,1,0,'{"task_id":9,"choice":1,"promised":8,"approved":8,"paid":8,"revenue":45,"feedback":"Under the negotiated rules, all eight crowns are approved and paid. The client price stays the same in this scenario; more of it reaches the worker.","edition":3,"task_title":"Beauty, with the rules visible"}'::jsonb),
(9,1,1,'{"task_id":9,"choice":1,"promised":8,"approved":2,"paid":2,"revenue":45,"feedback":"Under the existing terms, eight crowns are offered and two are approved and paid. The institution still controls the adjustment.","edition":3,"task_title":"Beauty, with the rules visible"}'::jsonb),
(9,1,2,'{"task_id":9,"choice":1,"promised":8,"approved":2,"paid":2,"revenue":45,"feedback":"The outside review is still pending. Under the existing rates, two of the offered eight crowns are approved and paid.","edition":3,"task_title":"Beauty, with the rules visible"}'::jsonb),
(9,2,0,'{"task_id":9,"choice":2,"promised":8,"approved":8,"paid":8,"revenue":45,"feedback":"Under the negotiated rules, all eight crowns are approved and paid. The client price stays the same in this scenario; more of it reaches the worker.","edition":3,"task_title":"Beauty, with the rules visible"}'::jsonb),
(9,2,1,'{"task_id":9,"choice":2,"promised":8,"approved":2,"paid":2,"revenue":45,"feedback":"Under the existing terms, eight crowns are offered and two are approved and paid. The institution still controls the adjustment.","edition":3,"task_title":"Beauty, with the rules visible"}'::jsonb),
(9,2,2,'{"task_id":9,"choice":2,"promised":8,"approved":2,"paid":2,"revenue":45,"feedback":"The outside review is still pending. Under the existing rates, two of the offered eight crowns are approved and paid.","edition":3,"task_title":"Beauty, with the rules visible"}'::jsonb)
on conflict(task_id,choice,reform) do update set result=excluded.result;
-- Included by the migration generator; apply 003-visual-max.sql instead.
create or replace function public.submit_visual_task(p_course uuid,p_task integer,p_response text,p_route integer default null) returns jsonb language plpgsql security definer set search_path='' as $$
declare e public.oracle_enrollments; r jsonb; n integer; v_choice integer; v_reform integer := -1;
begin
 if p_task is null or p_task not between 1 and 9 or p_response is null or char_length(trim(p_response)) not between 10 and 2000 then raise exception 'Write 10–2,000 characters for a valid assignment.'; end if;
 if p_task=7 and (p_route is null or p_route not between 0 and 2) then raise exception 'Choose a route.'; end if;
 select * into e from public.oracle_enrollments where course_id=p_course and user_id=auth.uid() for update;
 if not found then raise exception 'Join this class first.'; end if;
 select result into r from public.oracle_submissions where course_id=p_course and user_id=auth.uid() and task_id=p_task;
 if found then return r; end if;
 if e.completed_at is not null then raise exception 'This participation record is complete.'; end if;
 if not exists(select 1 from public.oracle_courses where id=p_course and active) then raise exception 'This class is closed.'; end if;
 if exists(select 1 from public.oracle_submissions where course_id=p_course and user_id=auth.uid() and coalesce(result->>'edition','')<>'3') then raise exception 'This record belongs to an earlier version. Ask your instructor for a new class code, or explore the updated game in practice.'; end if;
 select count(*) into n from public.oracle_submissions where course_id=p_course and user_id=auth.uid();
 if p_task<>n+1 then raise exception 'Complete assignments in order. Reload your saved progress.'; end if;
 v_choice:=case when p_task=7 then p_route when p_task=2 then 1 else 0 end;
 if p_task>7 then select choice into v_reform from public.oracle_submissions where course_id=p_course and user_id=auth.uid() and task_id=7; end if;
 select result into r from oracle_private.visual_outcomes where task_id=p_task and choice=v_choice and reform=v_reform;
 if r is null then raise exception 'Assignment configuration is missing.'; end if;
 r:=r||jsonb_build_object('response',trim(p_response));
 insert into public.oracle_submissions(course_id,user_id,task_id,choice,result) values(p_course,auth.uid(),p_task,v_choice,r);
 return r;
end $$;
revoke all on function public.submit_visual_task(uuid,integer,text,integer) from public,anon;
grant execute on function public.submit_visual_task(uuid,integer,text,integer) to authenticated;

-- Retire the older submission endpoint to prevent mixing editions.
revoke execute on function public.submit_written_task(uuid,integer,text,integer) from authenticated;

create or replace function public.reserve_oracle_dialogue(p_course uuid,p_request uuid,p_message text) returns jsonb language plpgsql security definer set search_path='' as $$
declare e public.oracle_enrollments; existing oracle_private.dialogue; limits oracle_private.ai_limits; used integer; hist jsonb;
begin
 if p_request is null or p_message is null or char_length(trim(p_message)) not between 10 and 1200 then raise exception 'Write 10–1,200 characters.'; end if;
 select * into e from public.oracle_enrollments where course_id=p_course and user_id=auth.uid() for update;
 if not found then raise exception 'Join this class first.'; end if;
 select * into existing from oracle_private.dialogue where request_id=p_request;
 if found then
  if existing.user_id<>auth.uid() or existing.course_id<>p_course then raise exception 'Request unavailable.'; end if;
  if existing.result is not null then return jsonb_build_object('cached',existing.result); end if;
  return jsonb_build_object('allowed',false,'reason','This exchange is already processing. Continue playing or reopen the conversation later.');
 end if;
 if e.completed_at is not null then return jsonb_build_object('allowed',false,'reason','This game is complete. You can review your saved conversation.'); end if;
 if not exists(select 1 from public.oracle_courses where id=p_course and active) then raise exception 'This class is closed.'; end if;
 select count(*) into used from oracle_private.dialogue where course_id=p_course and user_id=auth.uid();
 if used>=3 then return jsonb_build_object('allowed',false,'reason','You have used your three exchanges. Your participation credit does not depend on AI.'); end if;
 -- A shared locked row makes project-wide budgets safe under concurrent calls.
 select * into limits from oracle_private.ai_limits where id=1 for update;
 if not found then raise exception 'AI limits have not been configured.'; end if;
 if exists(select 1 from oracle_private.dialogue where user_id=auth.uid() and created_at>clock_timestamp()-interval '15 seconds') then return jsonb_build_object('allowed',false,'reason','Please allow 15 seconds between messages. You can continue without AI.'); end if;
 if (select count(*) from oracle_private.dialogue where created_at >= date_trunc('day',clock_timestamp() at time zone 'UTC') at time zone 'UTC')>=limits.daily_limit then return jsonb_build_object('allowed',false,'reason','The daily AI allowance is used up. Authored dialogue is available; your progress is unaffected.'); end if;
 if (select count(*) from oracle_private.dialogue where created_at>clock_timestamp()-interval '1 minute')>=limits.minute_limit then return jsonb_build_object('allowed',false,'reason','The AI desk is busy. Use the authored response or return later.'); end if;
 hist:=public.my_oracle_dialogue(p_course);
 insert into oracle_private.dialogue(request_id,course_id,user_id,message) values(p_request,p_course,auth.uid(),trim(p_message));
 return jsonb_build_object('allowed',true,'history',hist,'message',trim(p_message));
end $$;


commit;
