import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
const teacher='00000000-0000-0000-0000-000000000001',student='00000000-0000-0000-0000-000000000002',other='00000000-0000-0000-0000-000000000003';
test('database enforces authentication, ownership, sequence, completion and idempotency',async()=>{
 const db=new PGlite();
 await db.exec(`create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key,email text); create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$; grant usage on schema auth to authenticated; grant execute on function auth.uid() to authenticated;`);
 await db.exec(readFileSync(new URL('../backend/schema.sql',import.meta.url),'utf8'));
 await db.exec(readFileSync(new URL('../backend/outcomes.sql',import.meta.url),'utf8'));
 await db.query('insert into auth.users values($1,$2),($3,$4),($5,$6)',[teacher,'teacher@example.test',student,'student@example.test',other,'other@example.test']);
 const c=(await db.query("insert into public.oracle_courses(name,join_code,instructor_id) values('Test','class-secret-1234',$1) returning id",[teacher])).rows[0].id;
 await db.exec('set role anon');
 await assert.rejects(()=>db.query('select public.join_course($1)',['class-secret-1234']),/permission denied/);
 await db.exec('reset role; set role authenticated');
 await db.query("select set_config('request.jwt.claim.sub',$1,false)",[student]);
 await assert.rejects(()=>db.query('select public.my_progress($1)',[c]),/Join/);
 await db.query('select public.join_course($1)',['class-secret-1234']);
 await assert.rejects(()=>db.query('select public.instructor_records()'),/instructor/);
 await assert.rejects(()=>db.query('select * from public.oracle_enrollments'),/permission denied/);
 await assert.rejects(()=>db.query('select public.submit_task($1,2,0)',[c]),/in order/);
 await assert.rejects(()=>db.query('select public.submit_task($1,1,7)',[c]),/Invalid/);
 await assert.rejects(()=>db.query('select public.finish_game($1,$2)',[c,'A sufficiently long reflection written before doing the work.']),/nine/);
 for(let i=1;i<=9;i++)await db.query('select public.submit_task($1,$2,$3)',[c,i,i===2?1:0]);
 const before=(await db.query('select public.class_totals($1) as r',[c])).rows[0].r;
 assert.equal(before.contributions,9);assert.equal(before.paid,37);
 await db.query('select public.submit_task($1,1,2)',[c]);
 assert.deepEqual((await db.query('select public.class_totals($1) as r',[c])).rows[0].r,before);
 await assert.rejects(()=>db.query('select public.finish_game($1,$2)',[c,'short']),/40/);
 const first=(await db.query('select public.finish_game($1,$2) as r',[c,'The platform decided when payment arrived and who could dispute it.'])).rows[0].r;
 const repeated=(await db.query('select public.finish_game($1,$2) as r',[c,'Another reflection cannot replace a completed participation record.'])).rows[0].r;
 assert.deepEqual(first,repeated);
 await db.query("select set_config('request.jwt.claim.sub',$1,false)",[other]);
 await assert.rejects(()=>db.query('select public.my_progress($1)',[c]),/Join/);
 await assert.rejects(()=>db.query('select public.class_totals($1)',[c]),/Join/);
 await db.query('select public.join_course($1)',['class-secret-1234']);
 assert.equal((await db.query('select public.my_progress($1) as r',[c])).rows[0].r.entries.length,0);
 await db.query("select set_config('request.jwt.claim.sub',$1,false)",[teacher]);
 const roster=(await db.query('select public.instructor_records() as r')).rows[0].r;
 assert.equal(roster.length,2);assert.equal(roster.find(r=>r.email==='student@example.test').tasks_completed,9);
 await db.close();
});
