export const VERSION = '1.1';
export const stages = ['Dormant', 'Awakening', 'Prosperous', 'Magnificent'];
export const stageIndex = n => Math.min(3, Math.floor(n / 3));
export const acts = [
  {name:'The opportunity', line:'A little human judgment. A little machine magic.', note:'Welcome to The Below. Your judgments help the Oracle answer the kingdom. Complete nine assignments and a reflection. Your fictional earnings and answer choices do not determine your participation credit.'},
  {name:'A small adjustment', line:'Your flexibility is our greatest asset.', note:'The Oracle has secured new clients. Review conditions and payment arrangements have changed. Watch the difference between what was offered, what is approved, and what arrives.'},
  {name:'Who writes the rules?', line:'The kingdom needs another miracle. It needs you.', note:'You have a record of your work. Choose a response, then see what a change in the rules does to the next two assignments. This ending is a hypothetical scenario, not a prediction.'},
];
export const tasks = [
 {id:1,title:'A goose, with ambition',kind:'Creature classification',prompt:'A field report describes a feathered animal with two wings, a beak, webbed feet, and a tiny crown. It hisses at the royal surveyor.',rule:'Classify by physical features. Costumes do not change a creature’s species.',options:['Goose','Dragon','Insufficient evidence'],promised:6,revenue:30,paid:6,approved:6,oracle:'The Oracle has processed a royal creature report.',feedback:'Your classification enters the training archive. The Oracle receives 30 crowns; your six arrive as promised.',learning:'A classification task turns human observation into usable training data.'},
 {id:2,title:'The bridge that isn’t there',kind:'Answer review',prompt:'A traveler asks how to reach the mill. The map shows a ferry and a collapsed bridge. Which answer should the Oracle give?',rule:'Choose an answer supported by the supplied evidence.',options:['Cross the old bridge. It is perfectly safe.','Take the ferry; the bridge is marked as collapsed.','The mill cannot be reached by any route.'],promised:6,revenue:35,paid:6,approved:6,oracle:'The Oracle has reviewed a route to the mill.',feedback:'A human reviewer checks the answer before it reaches the traveler. The Herald credits the Oracle with excellent judgment.',learning:'Review and correction are productive work, even when the final product hides the reviewer.'},
 {id:3,title:'A compliment with teeth',kind:'Language interpretation',prompt:'A duke writes to a village: “Such lovely granaries. It would be a shame if the guards stopped visiting.” No other context is supplied.',rule:'Mark uncertainty when context could change the meaning.',options:['Certainly a friendly compliment','Certainly a direct order','Ambiguous; possibly an implied threat'],promised:8,revenue:40,paid:8,approved:8,oracle:'The Oracle has analyzed a delicate royal message.',feedback:'The archive now contains your interpretation. All eight crowns are paid. Above, a new ring of glass catches the light.',learning:'Language labeling depends on interpretation, context, and choices about categories.'},
 {id:4,title:'The invisible rule',kind:'Quality review',prompt:'A creature has scales, wings, and four legs. The public handbook says this is a dragon. Its wings have silver tips.',rule:'Use the public handbook: scales + wings + four legs = dragon.',options:['Dragon, according to the handbook','Wyvern','Request the missing silver-wing rule'],promised:8,revenue:45,paid:0,approved:0,oracle:'The Oracle’s creature archive has expanded.',feedback:'Rejected. The Inspector cites an unpublished rule: silver-tipped specimens require a separate label. Your work was processed, but none of the offered eight crowns is approved. No available answer could satisfy the undisclosed rule.',learning:'When standards are hidden, a worker cannot reliably know what will earn payment.'},
 {id:5,title:'One more tiny revision',kind:'Text correction',prompt:'Repair this instruction for the archive: “The ferry leave at dawn. Bring two coin.” This is a second pass on material already submitted.',rule:'Correct grammar without inventing new facts. The revision is mandatory.',options:['The ferry leaves at dawn. Bring two coins.','The ferry leaves at noon. Bring two coins.','The ferry leaves at dawn. Travel is free.'],promised:5,revenue:40,paid:1,approved:1,oracle:'The Oracle now speaks with impeccable grammar.',feedback:'Revision accepted. A “compensation adjustment” reduces five crowns to one. The work still creates a full-price answer upstairs.',learning:'Required rework and reduced compensation can shift quality-control costs onto workers.'},
 {id:6,title:'The Department of Continued Importance',kind:'Payment appeal',prompt:'Ten crowns are offered for auditing an overdue-payment record. The record confirms that work was delivered, but its payment has not arrived. What should your report say?',rule:'Document the dispute and request a remedy. Your response is recorded for participation.',options:['Attach the work record and request a payment date','File a support ticket and keep a copy','Record the unpaid work in a shared worker ledger'],promised:10,revenue:50,paid:0,approved:10,oracle:'The Oracle celebrates another successful commission.',feedback:'Audit approved: ten crowns. Payment received: zero. “Your payment is important to us. Your ticket has been forwarded to the Department of Continued Importance.” Approval is not the same as money arriving.',learning:'Delayed payment makes workers carry financial risk even after approval.'},
 {id:7,title:'An opening in the machinery',kind:'Choose your response',prompt:'A large commission is due. Coworkers have compared records and ask what to propose. Which route will you explore for the last two assignments?',rule:'This is your own scenario branch, not a live class vote. Every choice receives equal participation credit.',options:['Negotiate clear rules and guaranteed payment','Accept the existing terms and keep working','Pool records and pursue an independent appeal'],promised:0,revenue:0,paid:0,approved:0,oracle:'The Oracle awaits the next commission.',feedback:'Your response is recorded. The next two assignments show an explicitly fictional consequence of this choice.',learning:'Individual action, negotiation, and evidence-sharing offer different ways to respond to unequal power.'},
 {id:8,title:'The silver-wing specimen, again',kind:'Creature classification',prompt:'Another scaled creature has wings, four legs, and silver tips. You now have the missing appendix: silver-wing dragons must be labeled “silver dragon.”',rule:'Use the clarified appendix to classify this specimen.',options:['Silver dragon','Ordinary dragon','Wyvern'],promised:8,revenue:45,paid:2,approved:2,oracle:'The Oracle has identified a silver-wing specimen.',feedback:'The task is the same kind of work. The payment arrangement determines how its value reaches you.',learning:'Compare a change in institutional rules with simply asking a worker to try harder.'},
 {id:9,title:'A name beneath the answer',kind:'Contribution review',prompt:'The Herald wants to publish: “The Oracle independently verified the northern route.” The record shows that workers labeled reports and checked the answer.',rule:'Write a caption that accurately reflects the supplied production record.',options:['The Oracle independently verified everything.','Workers classified reports and reviewed the Oracle’s answer.','No human judgment was involved.'],promised:8,revenue:45,paid:2,approved:2,oracle:'The northern route report is ready for publication.',feedback:'The final answer is ready. Your ledger preserves the work underneath it. Look upstairs, then look at what arrived below.',learning:'Attribution affects whose expertise the public recognizes.'},
];
export function outcome(task, choice, reform) {
 if (!task || !Number.isInteger(choice) || choice < 0 || choice >= task.options.length) throw new Error('Choose one of the available responses.');
 let {promised,approved,paid,revenue,feedback}=task;
 if(task.id===2 && choice!==1){approved=paid=0;feedback='The reviewer rejects an answer unsupported by the map. The published standard explains why. Your response is recorded for participation, but this quality check earns no fictional pay. Compare this visible rule with the hidden rule in assignment four.';}
 if(task.id===7) feedback = ['In this scenario, the kingdom accepts clear standards and guaranteed payment on future assignments. Past unpaid work remains unresolved.','The existing arrangement continues. You retain access to assignments, including their uncertain payment terms.','In this scenario, an independent reviewer uses your records to release the ten pending crowns. Future rates remain unchanged.'][choice];
 if(task.id>=8 && reform===0){approved=paid=8; feedback='Under the negotiated rules, all eight crowns are approved and paid. The client price stays the same in this scenario; more of it reaches the worker.';}
 if(task.id>=8 && reform===1){feedback='Under the existing terms, eight crowns are offered and two are approved and paid. The institution still controls the adjustment.';}
 if(task.id===7 && choice===2){paid=10;feedback+=' The release is shown as a separate recovery of earlier pay.';}
 if(task.id>=8 && reform===2){feedback='The appeal recovered earlier pay, but did not change future contract terms: two of the offered eight crowns arrive.';}
 return {task_id:task.id,choice,promised,approved,paid,revenue,feedback};
}
export function summarize(entries=[]){return entries.reduce((s,e)=>{for(const k of ['promised','approved','paid','revenue'])s[k]+=e[k];s.count++;return s;},{promised:0,approved:0,paid:0,revenue:0,count:0});}
export function csvCell(value){const s=String(value??'');return '"'+(/^[\s]*[=+@-]/.test(s)?"'":"")+s.replaceAll('"','""')+'"';}
export function toCsv(rows){return '\uFEFF'+rows.map(r=>r.map(csvCell).join(',')).join('\r\n');}
