// Visual edition: response markers keep earlier submissions distinguishable.
export const visualEdition = 'Visual edition 2';
export const visualTasks = {
  1: {title:'A small creature. A large contribution.',kind:'Describe the circled subject',prompt:'Look closely at the circled animal. Give the Oracle as much useful detail as you can: features, colors, posture, position, and surroundings.',rule:'Separate what you can see from what you infer. It is fine to say that you are unsure.',image:'goose',circle:true,writing:'Describe the circled animal and the evidence for your identification.',learning:'A detailed image description is human knowledge turned into training data.',oracle:'The Oracle can now describe the natural world.'},
  2: {title:'The Oracle says: “a car.”',kind:'Verify and correct',prompt:'The Oracle has labeled this photograph “a car.” Does the image support that label? Correct it and describe the visible evidence.',rule:'Verify the label against the photograph. Do not invent a destination, speed, or passengers.',image:'train',writing:'Write a corrected label and explain the visible details that support it.',learning:'Correcting a confident machine label is skilled human work.',oracle:'The Oracle announces improved transport recognition.'},
  3: {title:'Which one is a circle?',kind:'Choose A, B, or C',prompt:'Three shapes. One circle. Select the matching image to add a label to the Oracle’s archive.',rule:'Choose the shape with a curved boundary and no corners. All responses count toward participation.',shapes:true,learning:'Even a simple label requires a person to interpret a category and apply a rule.',oracle:'The Oracle celebrates its mastery of geometry.'},
  4: {title:'Is this beautiful?',kind:'Judgment without a universal answer',prompt:'A Renaissance painting. A field of tulips. An abstract sculpture. Is each one beautiful? Give your own judgment and explain what shapes it.',rule:'Choose Yes, No, or Unsure for EACH image. You may give the same answer to several images. There is no universal correct taste.',beauty:true,writing:'Explain your judgments. What details, experiences, or expectations influenced you?',learning:'The rejection is scripted, not an assessment of your taste. Whose idea of beauty becomes the Oracle’s knowledge—and whose judgment gets erased?',oracle:'The Oracle claims to understand beauty.'},
  5: {title:'One more tiny revision',kind:'Caption repair',prompt:'A previous worker wrote: “Red stuff outside.” The client wants a more useful description of this photograph. Rewrite the caption.',rule:'Describe the flowers, their arrangement, colors, and setting. This extra pass is mandatory.',image:'tulips',writing:'Write a specific, evidence-based caption.',learning:'Required revisions can create more value while the institution reduces compensation.',oracle:'The Oracle produces beautifully detailed descriptions.'},
  6: {title:'A perfect image. An absent payment.',kind:'Audit the work record',prompt:'The job receipt below says the image description was delivered and approved. The payment is still pending. Audit the record and write an appeal.',receipt:true,writing:'Use the receipt to explain what is owed and request a specific remedy.',rule:'Distinguish delivered work, approved pay, and received pay. The amounts are fictional.',learning:'Approval is not payment. Workers can carry the financial risk after doing the work.',oracle:'The Oracle celebrates another successful image commission.'},
  8: {title:'Beauty, with the rules visible',kind:'Describe without ranking',prompt:'Look again at the abstract sculpture. This time, the client provides a clear standard: describe visible form, color, surface, and setting without ranking its beauty.',rule:'Describe what you see. Personal preference is not a quality criterion.',image:'sculpture',writing:'Describe the sculpture without deciding whether other people should find it beautiful.',learning:'Compare transparent instructions with the hidden standard in the earlier beauty task.',oracle:'The Oracle publishes a precise sculpture description.'},
  9: {title:'Who taught the Oracle to see?',kind:'Correct the credit',prompt:'The Herald captions this photograph: “The Oracle learned to see entirely by itself.” Your work record shows human descriptions, label corrections, and judgments.',rule:'Replace the claim with an accurate caption that recognizes the human work behind the system.',image:'train',writing:'Write the caption that should accompany the image.',learning:'The public sees the answer. Attribution can reveal the labor underneath it.',oracle:'The visual archive is ready. The workers’ record remains.'},
};
export const visuals={
 goose:{file:'goose.jpg',alt:'A brown-gray bird with a black neck and head, a pale cheek patch, and webbed feet stands on short green grass.',credit:'Kevin Kiefuik · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:Canada_Goose_Walking_on_Fairway.JPG',license:'https://creativecommons.org/licenses/by-sa/3.0/'},
 train:{file:'train.jpg',alt:'A large rail vehicle with a long body, cab windows, and wheels on railway tracks.',credit:'Albert Bergonzo · CC0',source:'https://commons.wikimedia.org/wiki/File:Locomotive_CC-65001.jpg',license:'https://creativecommons.org/publicdomain/zero/1.0/'},
 tulips:{file:'tulips.jpg',alt:'Rows of blooming tulips extend across a field, with green leaves beneath their colorful flowers.',credit:'Gogerr · CC0',source:'https://commons.wikimedia.org/wiki/File:Rows_of_Tulips_in_Pelham_Ontario.jpg',license:'https://creativecommons.org/publicdomain/zero/1.0/'},
 painting:{file:'painting.jpg',alt:'A Renaissance portrait of a young man with long fair hair looking back over his shoulder, one hand near his chest, against a green background.',credit:'Raphael · Bindo Altoviti, c. 1515 · National Gallery of Art · Public domain',source:'https://www.nga.gov/artworks/12131-bindo-altoviti',license:'https://www.nga.gov/open-access-policy'},
 sculpture:{file:'sculpture.jpg',alt:'A tall, slender, polished golden sculpture tapers upward from a pedestal, reducing a bird-like form to a smooth abstract curve.',credit:'Constantin Brâncuși · Bird in Space · Photo: Art Poskanzer · CC BY 2.0',source:'https://commons.wikimedia.org/wiki/File:Bird_in_Space.jpg',license:'https://creativecommons.org/licenses/by/2.0/'},
};
export function visualFeedback(id, original){
 if(id===2)return 'Correction recorded. The photograph shows a locomotive on rails, not a car. Your six crowns are fixed story pay, not an automated score for your description.';
 if(id===3)return 'Your shape label enters the archive. B is the circle: A has three straight sides and C has four. All eight crowns are fixed story pay; the choice does not determine participation credit.';
 if(id===4)return 'Rejected. The Inspector says your judgments do not match the client’s undisclosed beauty standard. This rejection happens regardless of your answers. It is a scripted demonstration of hidden standards—not an assessment of your taste. None of the offered eight crowns is approved.';
 if(id===5)return 'Revised caption accepted. A “compensation adjustment” reduces five crowns to one. Your extra descriptive work still creates a full-price answer upstairs.';
 return original;
}
export function encodeVisualResponse(task, form){
 if(task.id===3){const answer=form.get('shape');if(!['A','B','C'].includes(answer))throw new Error('Choose A, B, or C.');return `${visualEdition} · ${task.title}\nSelected shape: ${answer}`;}
 const text=String(form.get('response')||'').trim();
 if(text.length<10||text.length>1500)throw new Error('Write 10–1,500 characters.');
 let choices='';
 if(task.id===4){for(const key of ['painting','tulips','sculpture']){const answer=form.get(key);if(!['Yes','No','Unsure'].includes(answer))throw new Error('Give a judgment for each image.');choices+=`${key}: ${answer}\n`;}}
 return `${visualEdition} · ${task.title}\n${choices}${text}`;
}
export function isVisualResponse(response){return String(response||'').startsWith(visualEdition+' · ');}
